# .github/workflows/deploy_ecr.yaml
name: Deploy to ECR

on:
  push:
    branches:
    - dev # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker image
      run: |
        docker build -t ecr-jgl-deploy ./modulo_ecr_deploy

    - name: Tag Docker image
      run: |
        docker tag ecr-jgl-deploy:latest 248189943700.dkr.ecr.eu-west-1.amazonaws.com/ecr-jgl-deploy:latest

    - name: Push Docker image to ECR
      run: |
        docker push 248189943700.dkr.ecr.eu-west-1.amazonaws.com/ecr-jgl-deploy:latest
