name: Deploy Chat App

on:
  push:
    branches:
    - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform apply -auto-approve

  deploy_k8s:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Configure kubectl
      run: kubectl config set-cluster eks --server=${{ secrets.EKS_CLUSTER_ENDPOINT }} --certificate-authority=${{ secrets.EKS_CA_CERTIFICATE }}
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/chat-app-deployment.yaml
        kubectl apply -f k8s/chat-app-service.yaml
