apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: chat-app
  template:
    metadata:
      labels:
        app: chat-app
    spec:
      containers:
      - name: chat-app
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/chat-app-repo:latest  #
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
