apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  clusterIP: None # Especificamos None para que sea un servicio sin balanceo de carga
  selector:
    app: mysql # Asegura que el servicio seleccione los Pods del StatefulSet
