apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-service # El servicio que gestionará el StatefulSet
  replicas: 3 # Número de réplicas del StatefulSet
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password123" # Contraseña para el usuario root de MySQL
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql # Ruta donde MySQL almacenará los datos
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi # Tamaño del volumen persistente para cada réplica
      storageClassName: gp2 # Usamos el StorageClass de AWS
