apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-example
spec:
  capacity:
    storage: 1Gi # Define the size of the volume as 1 GB
  accessModes:
  - ReadWriteOnce # The volume can be mounted as read-write by a single node
  hostPath:
    path: "/mnt/data"
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
spec:
  accessModes:
  - ReadWriteOnce # The claim can access the volume with read-write by a single node
  resources:
    requests:
      storage: 1Gi
  volumeName: "pv-example"
  storageClassName: ""
