name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Status Badge
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const readmePath = path.join(process.env.GITHUB_WORKSPACE, 'README.md');
            const workflowName = 'CI Pipeline';
            const badgeUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/workflows/ci.yml/badge.svg`;
            const badgeMarkdown = `![${workflowName}](${badgeUrl})`;
            
            // Crear README.md si no existe
            if (!fs.existsSync(readmePath)) {
              fs.writeFileSync(readmePath, `# Mi Proyecto\n\n${badgeMarkdown}`);
            } else {
              let readme = fs.readFileSync(readmePath, 'utf8');
              if (!readme.includes(badgeMarkdown)) {
                readme = badgeMarkdown + '\n\n' + readme;
                fs.writeFileSync(readmePath, readme);
              }
            }