name: CI Pipeline
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Validate YAML Files
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint
          yamllint -c .yamllint . || true  
      
      - name: Print Message
        run: echo "Hello, CI/CD!"