name: Full CI/CD Pipeline
on:
  push:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      
      - name: Run Tests
        run: |
          pytest tests/ --junitxml=test-results/junit.xml
      
      - name: Upload Test Results
        uses: actions/upload-artifact@v3.1.0
        with:
          name: test-results
          path: test-results/junit.xml
      
      - name: Generate Coverage Report
        run: |
          pip install coverage
          coverage run -m pytest
          coverage xml -o coverage-report/coverage.xml
      
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3.1.0
        with:
          name: coverage-report
          path: coverage-report/coverage.xml